### ISSUE TITLE
VS Code prompt doesn't work well with function defined with @Pipe 

### ISSUE THREAD

**Issue by GongSiqiu** [JulienPalard/Pipe#81] opened 2022-07-10 07:07 UTC
In VS Code, when I hover mouse on a function name, it will prompt me the parameters. However, if the function is decorated by @ Pipe, it just tell me 
(function) xxx: Pipe
As there some solutions to it?

**Comment by JulienPalard** [comment] 2022-07-10 16:54
Hi!

Thanks for reporting!

Looks like an indirect duplicate of https://github.com/JulienPalard/Pipe/issues/76, you should subscribe to it and re-open the issue if typing does not help vs-code.

**Closed by JulienPalard** 2022-07-10 16:54 UTC
